
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carmenm
 */
public class Principal extends javax.swing.JFrame {
    private String a[] = new String[] { "cerillas", "patrulla", "papel", "azor",
                 "alerones", "conversar", "sollozo", "manzana" }; 
    private List<String> palabras = Arrays.asList(a); 
    private int vidas;
    private String tusletras;
    private String secreto;
    private int letrasfaltan;
    private int m;
    private String texto;
    
 
    /**
     * Creates new form Principal
     */
    public Principal() {      
        initComponents();
        this.vidas = 8;
        this.letrasfaltan = 0;
        this.tusletras = "";
        this.m = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIntentar = new javax.swing.JButton();
        txtLetra = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        lblResul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIntentar.setText("Intentar");
        btnIntentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntentarActionPerformed(evt);
            }
        });

        lblSalida.setText("Salida:");

        btnSalir.setText("Salir");

        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnIntentar)
                .addGap(222, 222, 222))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnJugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblResul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblResultado))
                        .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIntentar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblResultado))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblResul, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnJugar)))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
           Random aleatorio = new Random();
           // se escoge una palabra random de la lista que será el secreto
           secreto = palabras.get(aleatorio.nextInt(palabras.size()));
           int i = secreto.length();
           texto = "";
           // cadena vacia para rellenar con guiones bajos, para que el jugador
           // no vea la palabra secreta
           for (int a=0;a<secreto.length(); a++) // for method for displaying the correct word as dashes
           {
               texto += "_ ";
           } //dashes to represent the correct word.
           
           lblSalida.setText(String.valueOf(texto));
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnIntentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntentarActionPerformed

        //System.out.println(secreto);
        String tuletra = txtLetra.getText();
        String progreso = "";
        tusletras += tuletra;
        
        if (tuletra.length() < 1 || tuletra.length() >1) {
            lblSalida.setText("No es una entrada válida");
        }
        
        else {
        for(int a = 0; a < secreto.length(); a++) { 
        // si alguna letra contiene tuletra
           System.out.println(secreto.charAt(a));
        
        // por cada letra en secreto si algun letra de tusletras esta en secreto 
        // se imprime
        if (String.valueOf(secreto.charAt(a)).contains(tusletras)) {
        // aqui es donde quiero sustituir el guion por la letra acertada pero no me deja 
            char ch = tuletra.charAt(0);         
            int index = a; 
       
            texto = texto.substring(0, index) + ch + texto.substring(index + 1); 
            System.out.println(texto);
            lblSalida.setText(texto);
        }
        
        else {
             letrasfaltan ++;
         }
        
        }
        
         // si faltan cero letras se gana
        if (letrasfaltan == 0);
            lblResultado.setText("Has ganado");
        
        if (!secreto.contains(tuletra)){
            vidas --;
            lblResultado.setText("Esa letra no está");
        }
        
        else {
            lblResultado.setText("Bien, hay una " + tuletra +  " " + " en la palabra secreta");
        }
    
        if (vidas==0) {
            lblResultado.setText("Has perdido, la palabra es " + secreto);
        }
        }
    }//GEN-LAST:event_btnIntentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntentar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblResul;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JTextField txtLetra;
    // End of variables declaration//GEN-END:variables
}
